baseurl: ''
url: "https://wypiszsiezkosciola.pl" # the base hostname & protocol for your site, e.g. http://example.com
exclude: ['README.md']
permalink: pretty
title: Wypisz Się Z Kościoła
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: wypiszsiezkosc1

google_analytics_id: "G-J9QJGS5QDP"
homepage:
  show_call_box: false
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: ''

seo:
  meta_og_title: "Wypisz Się Z Kościoła"
  meta_og_type: "website"
  meta_og_url: "https://wypiszsiezkosciola.pl"
#  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Wypisz się z kościoła"
  meta_twitter_card: "summary"
  meta_twitter_site: "@wypiszsiezkosc1"
  meta_twitter_creator: "@wypiszsiezkosc1"

collections:
  tematy:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
